// space-sim/mission/script.ts
import type { MissionEvent, MissionState } from "./types";

export const STATE_DURATIONS: Record<MissionState, number> = {
  MISSION_INIT: 6, KSC_ESTABLISHING: 45, LAUNCH_PREPARATION: 70, CREW_PREPARATION: 50,
  COUNTDOWN: 80, ENGINE_IGNITION: 12, LIFTOFF: 28, ATMOSPHERIC_ASCENT: 75, BOOSTER_PHASE: 25,
  STAGE_TRANSITION: 30, ORBITAL_INSERTION: 25, ORBIT: 75, ISS_REVEAL: 50, ISS_APPROACH: 80,
  DOCKING_SEQUENCE: 100, DOCKING_COMPLETE: 12, CREW_TRANSFER: 33, ISS_INTERIOR_INTRO: 15,
  PLAYER_CONTROL_ENABLED: 0, ISS_EXPLORATION: Number.POSITIVE_INFINITY,
};

const E = (e: MissionEvent): MissionEvent => e;

export const MISSION_SCRIPT: MissionEvent[] = [
  // ---- MISSION_INIT (6s) ----
  E({ id: "init_01", state: "MISSION_INIT", at: 0, transition: "dip", hud: { met: true, phase: "ARTEMIS TRANSIT", progressStage: 1 } }),
  E({ id: "init_02", state: "MISSION_INIT", at: 2, comms: { speaker: "PAO", text: "Artemis Transit flight control is on console. Mission coverage begins shortly.", style: "pa" } }),
  // ---- KSC_ESTABLISHING (45s) ----
  E({ id: "ksc_01", state: "KSC_ESTABLISHING", at: 0, transition: "crossfade", shot: "est_wide", duration: 12, fx: { exposure: 0.9, glare: 0.4 },
      comms: { speaker: "PAO", text: "Kennedy Space Center, Florida. Six thirty-one a.m. Eastern.", style: "pa" } }),
  E({ id: "ksc_02", state: "KSC_ESTABLISHING", at: 12, transition: "cut", shot: "est_vab_crane", duration: 10, hud: { phase: "KENNEDY SPACE CENTER — LC-39" } }),
  E({ id: "ksc_03", state: "KSC_ESTABLISHING", at: 20, transition: "cut", shot: "vab_medium", duration: 8,
      comms: { speaker: "PAO", text: "The 325-foot Vehicle Assembly Building dominates the skyline — here, the Space Launch System that will carry Orion to the International Space Station was stacked.", style: "pa" } }),
  E({ id: "ksc_04", state: "KSC_ESTABLISHING", at: 28, transition: "cut", shot: "crawler_ground", duration: 9,
      comms: { speaker: "PAO", text: "Orion and the SLS ride the mobile launcher along the crawlerway to Pad 39-A.", style: "pa" } }),
  E({ id: "ksc_05", state: "KSC_ESTABLISHING", at: 37, transition: "cut", shot: "pad_wide", duration: 8, hud: { phase: "PAD 39-A — SLS / ORION" } }),
  // ---- LAUNCH_PREPARATION (70s) ----
  E({ id: "lp_01", state: "LAUNCH_PREPARATION", at: 0, transition: "cut", shot: "tower_low", duration: 10, hud: { phase: "LAUNCH PREPARATION — T-4 HOURS" },
      comms: { speaker: "CAPCOM", text: "Launch team is on console. Countdown clocks are running. T-minus four hours and holding for weather.", style: "radio" } }),
  E({ id: "lp_02", state: "LAUNCH_PREPARATION", at: 8, transition: "cut", shot: "svc_vehicles", duration: 8,
      comms: { speaker: "PAO", text: "Closeout crews service final consumables: cryogenic propellant, compressed gases, and electrical connections through the mobile launcher.", style: "pa" } }),
  E({ id: "lp_03", state: "LAUNCH_PREPARATION", at: 16, transition: "cut", shot: "rocket_closeup", duration: 9,
      comms: { speaker: "CAPCOM", text: "Frost lines are forming on the core stage — that's the cryo load doing its job.", style: "radio" } }),
  E({ id: "lp_04", state: "LAUNCH_PREPARATION", at: 25, transition: "cut", shot: "tower_closeup", duration: 8,
      comms: { speaker: "CAPCOM", text: "Swing arms are configured for launch. Weather is green across all recovery corridors.", style: "radio" } }),
  E({ id: "lp_05", state: "LAUNCH_PREPARATION", at: 33, transition: "cut", shot: "rocket_ecl", duration: 8,
      comms: { speaker: "PAO", text: "At 98 meters, the SLS is the most powerful rocket NASA has flown since the Saturn V.", style: "pa" } }),
  E({ id: "lp_06", state: "LAUNCH_PREPARATION", at: 41, transition: "cut", shot: "pad_ground_level", duration: 9,
      comms: { speaker: "CAPCOM", text: "Range is clear. Ground safety confirms pad perimeter is secure.", style: "radio" } }),
  E({ id: "lp_07", state: "LAUNCH_PREPARATION", at: 50, transition: "cut", shot: "pad_wide", duration: 10, fx: { exposure: 1.0 },
      comms: { speaker: "CAPCOM", text: "All stations, countdown will resume at T-minus one hour. Stand by for crew arrival.", style: "radio" } }),
  E({ id: "lp_08", state: "LAUNCH_PREPARATION", at: 60, transition: "cut", shot: "vab_closeup", duration: 10, hud: { phase: "LAUNCH PREPARATION — GO FOR TANKING" },
      comms: { speaker: "CAPCOM", text: "Launch vehicle is safed. Core stage tanking complete. Orion is configured for crew.", style: "radio" } }),
  // ---- CREW_PREPARATION (50s) ----
  E({ id: "cp_01", state: "CREW_PREPARATION", at: 0, transition: "dip", shot: "pov_crew_prep", duration: 12, hud: { phase: "CREW PREPARATION — O&C BUILDING" },
      comms: { speaker: "PAO", text: "Inside the Operations and Checkout Building, the crew suits up.", style: "pa" } }),
  E({ id: "cp_02", state: "CREW_PREPARATION", at: 10, comms: { speaker: "COMMANDER", text: "Com check. How do you hear me?", style: "radio" } }),
  E({ id: "cp_03", state: "CREW_PREPARATION", at: 18, comms: { speaker: "CAPCOM", text: "Read you loud and clear, Argo. You're one loud crew this morning.", style: "radio" } }),
  E({ id: "cp_04", state: "CREW_PREPARATION", at: 24, transition: "cut", shot: "cockpit_orion", duration: 12,
      comms: { speaker: "PAO", text: "The crew walks out, rides the elevator up the mobile launcher, and boards Orion through the crew access arm.", style: "pa" } }),
  E({ id: "cp_05", state: "CREW_PREPARATION", at: 36, comms: { speaker: "PILOT", text: "Restraints locked. Displays are up — vehicle looks beautiful from in here.", style: "crew" } }),
  E({ id: "cp_06", state: "CREW_PREPARATION", at: 44, transition: "cut", shot: "rocket_closeup", duration: 6,
      comms: { speaker: "CAPCOM", text: "Hatch is closed and locked. Cabin leak check in work.", style: "radio" } }),
  // ---- COUNTDOWN (80s) ----
  E({ id: "cd_01", state: "COUNTDOWN", at: 0, transition: "cut", shot: "pad_wide", duration: 10, hud: { phase: "FINAL COUNTDOWN", countdown: true },
      comms: { speaker: "CAPCOM", text: "T-minus ten minutes. All systems are nominal. Crew is ready.", style: "radio" } }),
  E({ id: "cd_02", state: "COUNTDOWN", at: 8, transition: "cut", shot: "tower_closeup", duration: 9,
      comms: { speaker: "CAPCOM", text: "Guidance is internal. Range is green.", style: "radio" } }),
  E({ id: "cd_03", state: "COUNTDOWN", at: 15, transition: "cut", shot: "rocket_side_track", duration: 8,
      comms: { speaker: "COMMANDER", text: "Orion's in the loop. We're go for launch.", style: "radio" } }),
  E({ id: "cd_04", state: "COUNTDOWN", at: 22, transition: "cut", shot: "vab_medium", duration: 8,
      comms: { speaker: "PAO", text: "T-minus five minutes. Inertial measurement alignment is complete.", style: "pa" } }),
  E({ id: "cd_05", state: "COUNTDOWN", at: 30, transition: "cut", shot: "rocket_ecl", duration: 8,
      comms: { speaker: "CAPCOM", text: "Flight computers are in startup. Launch vehicle is go.", style: "radio" } }),
  E({ id: "cd_06", state: "COUNTDOWN", at: 38, transition: "cut", shot: "pad_ground_level", duration: 10,
      comms: { speaker: "CAPCOM", text: "T-minus sixty seconds. Hydrogen burnoff igniters are active.", style: "radio" } }),
  E({ id: "cd_07", state: "COUNTDOWN", at: 48, transition: "cut", shot: "rocket_closeup", duration: 8,
      comms: { speaker: "CAPCOM", text: "Thirty seconds. Vehicle is on internal power. We are go for launch.", style: "radio" } }),
  E({ id: "cd_08", state: "COUNTDOWN", at: 56, transition: "cut", shot: "plume_ground", duration: 10,
      comms: { speaker: "CAPCOM", text: "Fifteen. Ten. Nine. Eight. Seven. Six.", style: "radio" } }),
  E({ id: "cd_09", state: "COUNTDOWN", at: 66, comms: { speaker: "CAPCOM", text: "Five. Four. Three. Two. One.", style: "radio" }, fx: { shake: 0.15 } }),
  E({ id: "cd_10", state: "COUNTDOWN", at: 74, comms: { speaker: "CAPCOM", text: "Ignition sequence start.", style: "radio" } }),
  // ---- ENGINE_IGNITION (12s) ----
  E({ id: "ig_01", state: "ENGINE_IGNITION", at: 0, transition: "cut", shot: "ignition_closeup", duration: 5, action: { kind: "ignite" }, fx: { shake: 0.6, exposure: 1.3, smoke: 1.0 },
      comms: { speaker: "CAPCOM", text: "Core stage engines are ignited.", style: "radio" } }),
  E({ id: "ig_02", state: "ENGINE_IGNITION", at: 5, transition: "cut", shot: "plume_ground", duration: 4,
      comms: { speaker: "PAO", text: "The four RS-25 engines build to full thrust — nearly nine million pounds with the boosters.", style: "pa" } }),
  E({ id: "ig_03", state: "ENGINE_IGNITION", at: 9, transition: "cut", shot: "tower_closeup", duration: 3,
      comms: { speaker: "CAPCOM", text: "All engines running. Booster ignition in three, two, one.", style: "radio" } }),
  // ---- LIFTOFF (28s) ----
  E({ id: "lo_01", state: "LIFTOFF", at: 0, transition: "cut", shot: "pad_ground_level", duration: 6, action: { kind: "liftoff" }, fx: { shake: 1.0, smoke: 1.0 },
      comms: { speaker: "CAPCOM", text: "Liftoff of Artemis Transit. The SLS has cleared Tower 39-A.", style: "radio" } }),
  E({ id: "lo_02", state: "LIFTOFF", at: 5, transition: "cut", shot: "rocket_side_track", duration: 7,
      comms: { speaker: "COMMANDER", text: "We have cleared the tower. Feels solid.", style: "radio" } }),
  E({ id: "lo_03", state: "LIFTOFF", at: 12, transition: "cut", shot: "rocket_distant_track", duration: 8, hud: { progressStage: 2 },
      comms: { speaker: "CAPCOM", text: "Vehicle is supersonic. Altitude four kilometers and climbing.", style: "radio" } }),
  E({ id: "lo_04", state: "LIFTOFF", at: 20, transition: "cut", shot: "rocket_upward", duration: 8,
      comms: { speaker: "PAO", text: "The twin solid rocket boosters burn for just over two minutes, providing most of the liftoff thrust.", style: "pa" } }),
  // ---- ATMOSPHERIC_ASCENT (75s) ----
  E({ id: "aa_01", state: "ATMOSPHERIC_ASCENT", at: 0, transition: "cut", shot: "booster_cam", duration: 8, hud: { phase: "ASCENT — MAX-Q" },
      comms: { speaker: "CAPCOM", text: "Max-Q. Maximum dynamic pressure.", style: "radio" } }),
  E({ id: "aa_02", state: "ATMOSPHERIC_ASCENT", at: 6, transition: "cut", shot: "horizon_ascent", duration: 9, fx: { exposure: 1.05 },
      comms: { speaker: "COMMANDER", text: "Throttling down through max-Q. Sky's getting dark up here.", style: "crew" } }),
  E({ id: "aa_03", state: "ATMOSPHERIC_ASCENT", at: 15, transition: "cut", shot: "cockpit_orion", duration: 8,
      comms: { speaker: "PILOT", text: "Cabin pressure nominal. Abort mode two armed.", style: "crew" } }),
  E({ id: "aa_04", state: "ATMOSPHERIC_ASCENT", at: 23, transition: "cut", shot: "rocket_distant_track", duration: 9,
      comms: { speaker: "CAPCOM", text: "Vehicle is through twenty kilometers. Trajectory is nominal.", style: "radio" } }),
  E({ id: "aa_05", state: "ATMOSPHERIC_ASCENT", at: 32, transition: "cut", shot: "stage_sep_side", duration: 7, action: { kind: "separateSrb" }, fx: { shake: 0.4 },
      comms: { speaker: "CAPCOM", text: "Booster separation confirmed.", style: "radio" } }),
  E({ id: "aa_06", state: "ATMOSPHERIC_ASCENT", at: 39, transition: "cut", shot: "horizon_ascent", duration: 9,
      comms: { speaker: "PAO", text: "The spent boosters fall away as the core stage carries Orion toward orbit on its RS-25 engines.", style: "pa" } }),
  E({ id: "aa_07", state: "ATMOSPHERIC_ASCENT", at: 48, transition: "cut", shot: "earth_wide", duration: 8, hud: { phase: "ASCENT — UPPER ATMOSPHERE" }, fx: { exposure: 0.95 } }),
  E({ id: "aa_08", state: "ATMOSPHERIC_ASCENT", at: 56, transition: "cut", shot: "rocket_upward", duration: 9,
      comms: { speaker: "CAPCOM", text: "Single engine core stage shutdown in preparation for staging.", style: "radio" } }),
  E({ id: "aa_09", state: "ATMOSPHERIC_ASCENT", at: 65, transition: "cut", shot: "stage_sep_wide", duration: 10, action: { kind: "separateCore" }, fx: { shake: 0.3 },
      comms: { speaker: "CAPCOM", text: "Core stage separation confirmed. ICPS is on the stack.", style: "radio" } }),
  // ---- BOOSTER_PHASE (25s) ----
  E({ id: "bp_01", state: "BOOSTER_PHASE", at: 0, transition: "cut", shot: "booster_cam", duration: 10, hud: { phase: "ASCENT — BOOSTER DESCENT" },
      comms: { speaker: "PAO", text: "The boosters tumble back toward the Atlantic, fitted with parachutes for recovery.", style: "pa" } }),
  E({ id: "bp_02", state: "BOOSTER_PHASE", at: 10, transition: "cut", shot: "icps_perspective", duration: 8,
      comms: { speaker: "COMMANDER", text: "We're riding quiet now. Good separation burn.", style: "crew" } }),
  E({ id: "bp_03", state: "BOOSTER_PHASE", at: 18, transition: "cut", shot: "starfield_hold", duration: 7, fx: { exposure: 0.9 } }),
  // ---- STAGE_TRANSITION (30s) ----
  E({ id: "st_01", state: "STAGE_TRANSITION", at: 0, transition: "cut", shot: "icps_perspective", duration: 10, hud: { phase: "ORBITAL BURN — ICPS" },
      comms: { speaker: "CAPCOM", text: "ICPS perigee raise burn, ten seconds.", style: "radio" } }),
  E({ id: "st_02", state: "STAGE_TRANSITION", at: 10, transition: "cut", shot: "earth_wide", duration: 12, fx: { exposure: 1.0 },
      comms: { speaker: "CAPCOM", text: "Burn is go. Velocity twenty-eight thousand kilometers per hour.", style: "radio" } }),
  E({ id: "st_03", state: "STAGE_TRANSITION", at: 22, transition: "cut", shot: "horizon_ascent", duration: 8,
      comms: { speaker: "CAPCOM", text: "Shutdown. Nominal insertion trajectory.", style: "radio" } }),
  // ---- ORBITAL_INSERTION (25s) ----
  E({ id: "oi_01", state: "ORBITAL_INSERTION", at: 0, transition: "cut", shot: "orion_exterior_orbit", duration: 10, action: { kind: "orbitInsertion" }, hud: { phase: "ORBITAL INSERTION", progressStage: 3 },
      comms: { speaker: "PAO", text: "Orion has separated from the ICPS. The spacecraft is now flying free in orbit, four hundred kilometers above Earth.", style: "pa" } }),
  E({ id: "oi_02", state: "ORBITAL_INSERTION", at: 10, transition: "cut", shot: "orion_rear_orbit", duration: 8,
      comms: { speaker: "COMMANDER", text: "Solar arrays deploying... arrays locked. Orion is healthy.", style: "crew" } }),
  E({ id: "oi_03", state: "ORBITAL_INSERTION", at: 18, transition: "cut", shot: "earth_limb_drift", duration: 7, fx: { exposure: 0.92, glare: 0.3 } }),
  // ---- ORBIT (75s) ----
  E({ id: "ob_01", state: "ORBIT", at: 0, transition: "dip", shot: "earth_wide", duration: 16, hud: { phase: "ORBIT — 400 KM" },
      comms: { speaker: "PAO", text: "From this altitude, the atmosphere is a thin blue line against the black of space.", style: "pa" } }),
  E({ id: "ob_02", state: "ORBIT", at: 14, transition: "cut", shot: "sunrise_orbit", duration: 14, fx: { exposure: 1.25, glare: 0.6 },
      comms: { speaker: "PILOT", text: "There's the sunrise. Sixteen orbits a day and it never gets old.", style: "crew" } }),
  E({ id: "ob_03", state: "ORBIT", at: 28, transition: "cut", shot: "orion_exterior_orbit", duration: 12,
      comms: { speaker: "CAPCOM", text: "Orion, Houston. You are go for far-field rendezvous with the International Space Station.", style: "radio" } }),
  E({ id: "ob_04", state: "ORBIT", at: 40, transition: "cut", shot: "starfield_hold", duration: 10, fx: { exposure: 0.85 },
      comms: { speaker: "COMMANDER", text: "Cabin lights down. Let's find the station.", style: "crew" } }),
  E({ id: "ob_05", state: "ORBIT", at: 50, transition: "cut", shot: "earth_limb_drift", duration: 12,
      comms: { speaker: "PAO", text: "Below, city lights trace the coastlines of the night side.", style: "pa" } }),
  E({ id: "ob_06", state: "ORBIT", at: 62, transition: "cut", shot: "orion_rear_orbit", duration: 13,
      comms: { speaker: "CAPCOM", text: "Radar has a track. Station is eighty kilometers ahead, closing slowly.", style: "radio" } }),
  // ---- ISS_REVEAL (50s) ----
  E({ id: "ir_01", state: "ISS_REVEAL", at: 0, transition: "dip", shot: "starfield_hold", duration: 12, hud: { phase: "APPROACH — ACQUIRING TARGET", progressStage: 4 },
      comms: { speaker: "PAO", text: "Out of the darkness, a structure takes shape — the International Space Station.", style: "pa" } }),
  E({ id: "ir_02", state: "ISS_REVEAL", at: 10, transition: "crossfade", shot: "iss_reveal_far", duration: 14, fx: { exposure: 1.0 } }),
  E({ id: "ir_03", state: "ISS_REVEAL", at: 24, transition: "cut", shot: "iss_reveal_close", duration: 14,
      comms: { speaker: "COMMANDER", text: "There she is. Solar wings are out. She looks great.", style: "crew" } }),
  E({ id: "ir_04", state: "ISS_REVEAL", at: 38, transition: "cut", shot: "solar_array_perspective", duration: 12,
      comms: { speaker: "PAO", text: "The station spans 109 meters — larger than a football field, home to crews continuously for over two decades.", style: "pa" } }),
  // ---- ISS_APPROACH (80s) ----
  E({ id: "ia_01", state: "ISS_APPROACH", at: 0, transition: "cut", shot: "iss_approach_track", duration: 14, hud: { phase: "APPROACH — R-BAR", telemetry: "docking" },
      comms: { speaker: "CAPCOM", text: "Orion, Houston. You are go for approach corridor entry. Station is in free drift.", style: "radio" } }),
  E({ id: "ia_02", state: "ISS_APPROACH", at: 12, transition: "cut", shot: "docking_target_cam", duration: 12,
      comms: { speaker: "CAPCOM", text: "Range two hundred meters. You're slightly left of the centerline — corrected.", style: "radio" } }),
  E({ id: "ia_03", state: "ISS_APPROACH", at: 24, transition: "cut", shot: "iss_earth_facing", duration: 12,
      comms: { speaker: "PILOT", text: "Station is holding attitude. Approach looks clean.", style: "crew" } }),
  E({ id: "ia_04", state: "ISS_APPROACH", at: 36, transition: "cut", shot: "iss_approach_track", duration: 14,
      comms: { speaker: "CAPCOM", text: "Hold at one hundred fifty meters. Attitude is stable — proceeding.", style: "radio" } }),
  E({ id: "ia_05", state: "ISS_APPROACH", at: 50, transition: "cut", shot: "docking_target_cam", duration: 14,
      comms: { speaker: "CAPCOM", text: "Range one hundred meters. Closing rate is nominal. Docking target alignment is good.", style: "radio" } }),
  E({ id: "ia_06", state: "ISS_APPROACH", at: 64, transition: "cut", shot: "orion_exterior_orbit", duration: 8, fx: { exposure: 0.98 },
      comms: { speaker: "COMMANDER", text: "Final approach mode. Taking it slow and steady.", style: "crew" } }),
  E({ id: "ia_07", state: "ISS_APPROACH", at: 72, transition: "cut", shot: "docking_side_cam", duration: 8,
      comms: { speaker: "CAPCOM", text: "Thirty meters. Stand by for soft capture sequence.", style: "radio" } }),
  // ---- DOCKING_SEQUENCE (100s) ----
  E({ id: "ds_01", state: "DOCKING_SEQUENCE", at: 0, transition: "cut", shot: "docking_target_cam", duration: 16, hud: { phase: "DOCKING — SOFT CAPTURE", telemetry: "docking" },
      comms: { speaker: "CAPCOM", text: "Range twenty meters. Closure rate five centimeters per second.", style: "radio" } }),
  E({ id: "ds_02", state: "DOCKING_SEQUENCE", at: 14, transition: "cut", shot: "docking_side_cam", duration: 14,
      comms: { speaker: "CAPCOM", text: "Ten meters. Alignment indicator is green across the board.", style: "radio" } }),
  E({ id: "ds_03", state: "DOCKING_SEQUENCE", at: 28, transition: "cut", shot: "docking_contact_ecl", duration: 14, action: { kind: "dockContact" }, fx: { shake: 0.08 },
      comms: { speaker: "CAPCOM", text: "Contact. Soft capture confirmed.", style: "radio" } }),
  E({ id: "ds_04", state: "DOCKING_SEQUENCE", at: 42, transition: "cut", shot: "docking_target_cam", duration: 12, action: { kind: "dockCapture" },
      comms: { speaker: "PAO", text: "Twelve hooks engage around the docking ring, pulling Orion to a hard seal.", style: "pa" } }),
  E({ id: "ds_05", state: "DOCKING_SEQUENCE", at: 54, transition: "cut", shot: "iss_earth_facing", duration: 12, action: { kind: "dockHard" }, fx: { shake: 0.05 },
      comms: { speaker: "CAPCOM", text: "Hard dock confirmed. Relative motion is zero. Orion and the International Space Station are one vehicle.", style: "radio" } }),
  E({ id: "ds_06", state: "DOCKING_SEQUENCE", at: 66, transition: "cut", shot: "docking_side_cam", duration: 12,
      comms: { speaker: "COMMANDER", text: "Copy hard dock. Pressure equalization in work.", style: "crew" } }),
  E({ id: "ds_07", state: "DOCKING_SEQUENCE", at: 78, transition: "cut", shot: "iss_reveal_close", duration: 10, hud: { telemetry: "off" },
      comms: { speaker: "CAPCOM", text: "Houston is showing vestibule pressure stable. You are go to open the hatches.", style: "radio" } }),
  E({ id: "ds_08", state: "DOCKING_SEQUENCE", at: 88, transition: "cut", shot: "orion_exterior_orbit", duration: 12,
      comms: { speaker: "PAO", text: "Docking complete — five hours and fifty-two minutes into the flight.", style: "pa" } }),
  // ---- DOCKING_COMPLETE (12s) ----
  E({ id: "dc_01", state: "DOCKING_COMPLETE", at: 0, transition: "cut", shot: "docking_contact_ecl", duration: 12, hud: { phase: "DOCKING COMPLETE", progressStage: 5 },
      comms: { speaker: "COMMANDER", text: "Thanks Houston. Let's go visit the neighbors.", style: "crew" } }),
  // ---- CREW_TRANSFER (33s) ----
  E({ id: "ct_01", state: "CREW_TRANSFER", at: 0, transition: "dip", shot: "pov_hatch_open", duration: 14, hud: { phase: "HATCH OPERATIONS" },
      comms: { speaker: "PAO", text: "Inside Orion, the crew equalizes the pressure, opens the forward hatch, and floats into the docking tunnel.", style: "pa" } }),
  E({ id: "ct_02", state: "CREW_TRANSFER", at: 12, action: { kind: "openHatch" },
      comms: { speaker: "COMMANDER", text: "Hatch is open. Here we go.", style: "crew" } }),
  E({ id: "ct_03", state: "CREW_TRANSFER", at: 21, transition: "cut", shot: "pov_transfer", duration: 12,
      comms: { speaker: "PILOT", text: "Hello, Harmony. It's been a while.", style: "crew" } }),
  // ---- ISS_INTERIOR_INTRO (15s) ----
  E({ id: "ii_01", state: "ISS_INTERIOR_INTRO", at: 0, transition: "dip", shot: "iss_interior_establish", duration: 15, action: { kind: "enterInterior" }, hud: { phase: "INTERNATIONAL SPACE STATION" },
      comms: { speaker: "PAO", text: "Welcome aboard. Beyond this vestibule: the laboratory, the Cupola, and the view of a lifetime.", style: "pa" } }),
  // ---- PLAYER_CONTROL_ENABLED (0s) ----
  E({ id: "pc_01", state: "PLAYER_CONTROL_ENABLED", at: 0, transition: "cut", shot: "cupola_earth_gaze", duration: 4, action: { kind: "enablePlayer" },
      hud: { phase: "EXPLORATION — YOU HAVE CONTROL", progressStage: 6 },
      comms: { speaker: "COMMANDER", text: "You have the vehicle. Explore the station — and don't miss the Cupola.", style: "crew" } }),
];
